repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: zuban
        name: zuban
        entry: zuban check src/serf tests
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
  # Prettier - formats Markdown (and other files)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0  # Use the latest version
    hooks:
      - id: prettier
        types_or: [markdown]
        additional_dependencies:
          - prettier@3.1.0
