"""Typed record schemas for the Amazon-Google Products match task.

Source: Köpcke, Thor and Rahm, "Evaluation of entity resolution approaches on
real-world match tasks", PVLDB 3(1), 2010, Table 1 and Section 3.1. The task
joins 1,363 Amazon.com products against 3,226 products from Google's product
search (Google Base Data API) with 1,300 gold correspondences over product name,
description, manufacturer and price. The Google side was generated by querying
Google Base with the Amazon product names, so one Amazon product may appear as
several Google listings from different merchants. Only UPC-bearing products were
kept, but the UPC is not part of the released attributes. It is the hardest of
the paper's four tasks: no evaluated approach exceeded 62% F-measure.

Mudgal et al., SIGMOD 2018 (DeepMatcher, Table 3 and Section 5.1) classify this
as a structured software-domain task with three attributes and report the largest
gap in their study between deep learning (69.3% F1) and the string-similarity
baseline Magellan (49.1% F1), explaining it directly: "the product titles across
matching pairs from the source datasets (Amazon and Google) correspond to
synonyms of one another. That is, they are semantically similar but have large
string similarity distances." Matching therefore has to be semantic.

In the DeepMatcher packaging used here, ``tableA.csv`` is the Amazon side and
``tableB.csv`` is the Google side. This was verified against the raw archive,
whose ``tableA`` ids are Amazon ASINs and whose ``tableB`` ids are
``google.com/base/feeds/snippets`` URLs, and against Table 1 of the Köpcke paper,
which gives 1,363 Amazon and 3,226 Google records.
"""

from pydantic import Field

from serf.dspy.schemas.base import (
    EntityMatchCandidate,
    EntitySide,
    SourcePrice,
    SourceText,
)

AMAZON_SOURCE_NAME = "Amazon.com"
GOOGLE_SOURCE_NAME = "Google Products"


class AmazonSoftwareProduct(EntitySide):
    """An Amazon.com product listing, mostly consumer and business software.

    Amazon titles are lower-cased catalog titles that spell out edition, platform,
    licence type and pack size. Cited from Köpcke, Thor and Rahm, PVLDB 3(1),
    2010, Section 3.1 and Mudgal et al., SIGMOD 2018, Section 5.1.

    Parameters
    ----------
    title : str
        Lower-cased Amazon catalog title including edition and licence details
    manufacturer : str
        Software publisher or hardware vendor
    price : float | None
        Amazon price in US dollars, frequently missing or zero in this snapshot
    """

    source_name: SourceText = Field(
        default=AMAZON_SOURCE_NAME,
        description="Always Amazon.com, the catalog side of this match task",
    )
    title: SourceText = Field(
        default="",
        description=(
            "Lower-cased Amazon catalog title, for example 'ca international - "
            "arcserve lap/desktop oem 30pk'. It usually spells out edition, version, "
            "platform, licence type (oem, upgrade, academic) and seat or pack count. "
            "The Google side often expresses the same product with different words, "
            "so compare meaning rather than string overlap, but treat a differing "
            "version number, platform or seat count as a different product."
        ),
    )
    manufacturer: SourceText = Field(
        default="",
        description=(
            "Software publisher or vendor, lower-cased, for example 'broderbund' or "
            "'computer associates'. Present far more often than on the Google side."
        ),
    )
    price: SourcePrice = Field(
        default=None,
        description=(
            "Amazon price in US dollars. Frequently missing or zero in this snapshot, "
            "so it is close to useless as matching evidence."
        ),
    )


class GoogleSoftwareProduct(EntitySide):
    """A product listing from Google's product search (Google Base).

    These are merchant listings harvested by querying Google Base with Amazon
    product names, so titles are marketplace wording rather than catalog wording
    and several listings can refer to one Amazon product. Cited from Köpcke, Thor
    and Rahm, PVLDB 3(1), 2010, Section 3.1 and Mudgal et al., SIGMOD 2018,
    Section 5.1.

    Parameters
    ----------
    title : str
        Merchant listing title, often shorter or reworded relative to Amazon
    manufacturer : str
        Publisher or vendor, blank for most listings
    price : float | None
        Merchant price in US dollars, usually present
    """

    source_name: SourceText = Field(
        default=GOOGLE_SOURCE_NAME,
        description=(
            "Always Google Products (Google Base): third-party merchant listings "
            "retrieved by querying with Amazon product names"
        ),
    )
    title: SourceText = Field(
        default="",
        description=(
            "Merchant listing title, for example 'learning quickbooks 2007'. Often "
            "much shorter than the Amazon title, or a synonym of it with almost no "
            "shared tokens, which is exactly why string similarity fails on this "
            "task. Version numbers, years and platform tokens that do appear are "
            "reliable and must agree."
        ),
    )
    manufacturer: SourceText = Field(
        default="",
        description=(
            "Publisher or vendor, blank for most listings because merchants omit it. "
            "A blank value is not evidence against a match."
        ),
    )
    price: SourcePrice = Field(
        default=None,
        description=(
            "Merchant price in US dollars, usually present. Merchants undercut and "
            "bundle, so prices differ from Amazon's even for identical products; a "
            "price that is off by an order of magnitude does suggest a different "
            "edition or a bundle."
        ),
    )


class AmazonGoogleCandidate(EntityMatchCandidate):
    """An Amazon.com product paired with a Google Products listing.

    Parameters
    ----------
    left : AmazonSoftwareProduct
        The Amazon.com catalog product
    right : GoogleSoftwareProduct
        The Google Products merchant listing
    """

    left: AmazonSoftwareProduct = Field(
        description="The Amazon.com catalog product, copied from the input"
    )
    right: GoogleSoftwareProduct = Field(
        description="The Google Products merchant listing, copied from the input"
    )
